// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzKz8CHDX9BWQ70G8v66zlRaK_4T_EvGw',
    appId: '1:787243015560:web:a6f7919efcb3bd53f72e3d',
    messagingSenderId: '787243015560',
    projectId: 'whatsapp-clone-flutter-d3185',
    authDomain: 'whatsapp-clone-flutter-d3185.firebaseapp.com',
    storageBucket: 'whatsapp-clone-flutter-d3185.appspot.com',
    measurementId: 'G-61GC9RETZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPxEQTAddP9w873Q75yqbZx0VqMx5FGEA',
    appId: '1:787243015560:android:acedb011020e367cf72e3d',
    messagingSenderId: '787243015560',
    projectId: 'whatsapp-clone-flutter-d3185',
    storageBucket: 'whatsapp-clone-flutter-d3185.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDli-udtJpx_dCr6cEouShU9naV1kBnS5E',
    appId: '1:787243015560:ios:8ad895f5f5d5a960f72e3d',
    messagingSenderId: '787243015560',
    projectId: 'whatsapp-clone-flutter-d3185',
    storageBucket: 'whatsapp-clone-flutter-d3185.appspot.com',
    iosBundleId: 'com.example.whatsappCloneFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDli-udtJpx_dCr6cEouShU9naV1kBnS5E',
    appId: '1:787243015560:ios:8ad895f5f5d5a960f72e3d',
    messagingSenderId: '787243015560',
    projectId: 'whatsapp-clone-flutter-d3185',
    storageBucket: 'whatsapp-clone-flutter-d3185.appspot.com',
    iosBundleId: 'com.example.whatsappCloneFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzKz8CHDX9BWQ70G8v66zlRaK_4T_EvGw',
    appId: '1:787243015560:web:b9087b1f44a187f6f72e3d',
    messagingSenderId: '787243015560',
    projectId: 'whatsapp-clone-flutter-d3185',
    authDomain: 'whatsapp-clone-flutter-d3185.firebaseapp.com',
    storageBucket: 'whatsapp-clone-flutter-d3185.appspot.com',
    measurementId: 'G-KRDF0MBYPH',
  );
}
